In [346]:
import pandas as pd
import numpy as np
import seaborn as sb
# regression models
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge, ElasticNet, Lasso, LinearRegression
from sklearn import ensemble
# performance and processing
from sklearn.model_selection import train_test_split, KFold, cross_val_score, cross_validate
from sklearn import metrics, preprocessing

In [347]:
school_df = pd.read_csv('scorecard_dataset_imputed.csv')

In [348]:
school_df

School Name School State    Zip Code  \
0                          Alabama A & M University           AL       35762   
1               University of Alabama at Birmingham           AL  35294-0110   
2               University of Alabama in Huntsville           AL       35899   
3                          Alabama State University           AL  36104-0271   
4                         The University of Alabama           AL  35487-0100   
...                                             ...          ...         ...   
1653                            Milligan University           TN       37682   
1654                              Husson University           ME  04401-2929   
1655  Indiana Wesleyan University-National & Global           IN       46953   
1656                       Purdue University Global           IN       47906   
1657                            Carolina University           NC       27101   

      School Locale  Rate of Full Time Faculty  Faculty Avg. Salary  \
0                12                     0.7110               7709.0   
1                12                     0.7754              11049.0   
2                12                     0.6434               9688.0   
3                12                     0.6501               7221.0   
4                12                     0.7604              10291.0   
...             ...                        ...                  ...   
1653             22                     0.9907               6173.0   
1654             13                     0.9778               7297.0   
1655             41                     1.0000               7320.0   
1656             11                     0.2084               4775.0   
1657             12                     0.3404               3380.0   

      Enrollment Size  Percent Males  Percent Females  4 Year Retention Rate  \
0              5271.0         0.3967           0.6033                0.56890   
1             13328.0         0.3890           0.6110                0.83100   
2              7785.0         0.5810           0.4190                0.82910   
3              3750.0         0.3691           0.6309                0.61270   
4             31900.0         0.4451           0.5549                0.86930   
...               ...            ...              ...                    ...   
1653            796.0         0.4648           0.5352                0.74290   
1654           2642.0         0.4383           0.5617                0.72800   
1655           6859.0         0.2674           0.7326                0.64189   
1656          28106.0         0.3539           0.6461                1.00000   
1657            348.0         0.5316           0.4684                0.64040   

      ...  150% 4 Year Completion Rate (Pooled)  \
0     ...                                0.2844   
1     ...                                0.6090   
2     ...                                0.5483   
3     ...                                0.3142   
4     ...                                0.7149   
...   ...                                   ...   
1653  ...                                0.6622   
1654  ...                                0.5645   
1655  ...                                0.3754   
1656  ...                                0.2654   
1657  ...                                0.3871   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
0                                    0.331126                    0.176   
1                                    0.571058                    0.063   
2                                    0.588311                    0.065   
3                                    0.289705                    0.180   
4                                    0.635813                    0.054   
...                                       ...                      ...   
1653                                 0.722611                    0.036   
1654                                 0.641234               

In [349]:
school_df.describe()

School Locale  Rate of Full Time Faculty  Faculty Avg. Salary  \
count    1658.000000                1658.000000          1658.000000   
mean       19.953559                   0.644689          8029.757997   
std         9.418565                   0.266937          2509.039360   
min        11.000000                   0.000000           963.000000   
25%        12.000000                   0.451675          6423.250000   
50%        21.000000                   0.662500          7655.500000   
75%        31.000000                   0.876075          9286.750000   
max        43.000000                   1.000000         20988.000000   

       Enrollment Size  Percent Males  Percent Females  4 Year Retention Rate  \
count      1658.000000    1658.000000      1658.000000            1658.000000   
mean       5030.932726       0.416610         0.571925               0.739733   
std        7304.231443       0.137087         0.143434               0.141556   
min           0.000000       0.000000         0.000000               0.000000   
25%        1002.500000       0.363350         0.511725               0.666700   
50%        2041.500000       0.423850         0.572000               0.752650   
75%        5727.500000       0.483200         0.633225               0.830550   
max       53119.000000       1.000000         1.000000               1.000000   

       Median Househould Income  Avg. Age of Entry  Admission Rate  ...  \
count               1658.000000        1658.000000     1658.000000  ...   
mean               63040.818683          22.398673        0.681397  ...   
std                12441.200781           3.465275        0.197417  ...   
min                17277.000000          19.000000        0.019700  ...   
25%                56191.750000          20.000000        0.582950  ...   
50%                63377.500000          21.000000        0.709750  ...   
75%                71684.500000          24.000000        0.814192  ...   
max                96737.000000          40.000000        1.000000  ...   

       150% 4 Year Completion Rate (Pooled)  \
count                           1658.000000   
mean                               0.544533   
std                                0.192021   
min                                0.000000   
25%                                0.414050   
50%                                0.546100   
75%                                0.673025   
max                                1.000000   

       Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
count                              1658.000000              1658.000000   
mean                                  0.652625                 0.072227   
std                                   0.165025                 0.050892   
min                                   0.139981                 0.000000   
25%                                   0.565460                 0.036000   
50%                                   0.672572                 0.062000   
75%                                   0.774394                 0.093000   
max                                   0.945070                 0.370000   

       Undergraduate Federal Loan Repayment Rate     Catholic  \
count                                1658.000000  1658.000000   
mean                                    0.970691     0.109168   
std                                     0.069366     0.311944   
min                                     0.571806     0.000000   
25%                                     0.936457     0.000000   
50%                                     0.979905     0.000000   
75%                                     1.016651     0.000000   
max                                     1.134698     1.000000   

       Average Net Price  Out-In State Tuition Ratio  Debt to Earnings Ratio  \
count        1658.000000                 1658.000000             1658.000000   
mean        20516.743297                    1.410734                0.735505   
std          7840.188753  

In [350]:
# Obtain counts of missing entries for each column
null_counts = []
for col in school_df:
    variable = {}
    count = school_df[col].isnull().sum()
    variable[col] = count
    null_counts.append(variable)
null_counts  
# Should be no missing data, since JMP was used for imputation

[{'School Name': 0},
 {'School State': 0},
 {'Zip Code': 0},
 {'School Locale': 0},
 {'Rate of Full Time Faculty': 0},
 {'Faculty Avg. Salary': 0},
 {'Enrollment Size': 0},
 {'Percent Males': 0},
 {'Percent Females': 0},
 {'4 Year Retention Rate': 0},
 {'Median Househould Income': 0},
 {'Avg. Age of Entry': 0},
 {'Admission Rate': 0},
 {'Avg. Cost': 0},
 {'Percent that Received Pell Grant': 0},
 {'Percent of Undergraduates that Receive Federal Loan': 0},
 {'150% 4 Year Completion Rate (Pooled)': 0},
 {'Percent Repaying Not in Default 5 Years': 0},
 {'Three Year Default Rate': 0},
 {'Undergraduate Federal Loan Repayment Rate': 0},
 {'Catholic': 0},
 {'Average Net Price': 0},
 {'Out-In State Tuition Ratio': 0},
 {'Debt to Earnings Ratio': 0},
 {'Male to Female Ratio': 21},
 {'Cluster (hier)': 0}]

In [351]:
school_df

School Name School State    Zip Code  \
0                          Alabama A & M University           AL       35762   
1               University of Alabama at Birmingham           AL  35294-0110   
2               University of Alabama in Huntsville           AL       35899   
3                          Alabama State University           AL  36104-0271   
4                         The University of Alabama           AL  35487-0100   
...                                             ...          ...         ...   
1653                            Milligan University           TN       37682   
1654                              Husson University           ME  04401-2929   
1655  Indiana Wesleyan University-National & Global           IN       46953   
1656                       Purdue University Global           IN       47906   
1657                            Carolina University           NC       27101   

      School Locale  Rate of Full Time Faculty  Faculty Avg. Salary  \
0                12                     0.7110               7709.0   
1                12                     0.7754              11049.0   
2                12                     0.6434               9688.0   
3                12                     0.6501               7221.0   
4                12                     0.7604              10291.0   
...             ...                        ...                  ...   
1653             22                     0.9907               6173.0   
1654             13                     0.9778               7297.0   
1655             41                     1.0000               7320.0   
1656             11                     0.2084               4775.0   
1657             12                     0.3404               3380.0   

      Enrollment Size  Percent Males  Percent Females  4 Year Retention Rate  \
0              5271.0         0.3967           0.6033                0.56890   
1             13328.0         0.3890           0.6110                0.83100   
2              7785.0         0.5810           0.4190                0.82910   
3              3750.0         0.3691           0.6309                0.61270   
4             31900.0         0.4451           0.5549                0.86930   
...               ...            ...              ...                    ...   
1653            796.0         0.4648           0.5352                0.74290   
1654           2642.0         0.4383           0.5617                0.72800   
1655           6859.0         0.2674           0.7326                0.64189   
1656          28106.0         0.3539           0.6461                1.00000   
1657            348.0         0.5316           0.4684                0.64040   

      ...  150% 4 Year Completion Rate (Pooled)  \
0     ...                                0.2844   
1     ...                                0.6090   
2     ...                                0.5483   
3     ...                                0.3142   
4     ...                                0.7149   
...   ...                                   ...   
1653  ...                                0.6622   
1654  ...                                0.5645   
1655  ...                                0.3754   
1656  ...                                0.2654   
1657  ...                                0.3871   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
0                                    0.331126                    0.176   
1                                    0.571058                    0.063   
2                                    0.588311                    0.065   
3                                    0.289705                    0.180   
4                                    0.635813                    0.054   
...                                       ...                      ...   
1653                                 0.722611                    0.036   
1654                                 0.641234               

In [352]:
dep_cols = [
    '4 Year Retention Rate',
    '150% 4 Year Completion Rate (Pooled)',
    'Debt to Earnings Ratio',
]
dependent = school_df[dep_cols]

In [353]:
dependent

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
0                   0.56890                                0.2844   
1                   0.83100                                0.6090   
2                   0.82910                                0.5483   
3                   0.61270                                0.3142   
4                   0.86930                                0.7149   
...                     ...                                   ...   
1653                0.74290                                0.6622   
1654                0.72800                                0.5645   
1655                0.64189                                0.3754   
1656                1.00000                                0.2654   
1657                0.64040                                0.3871   

      Debt to Earnings Ratio  
0                   1.314015  
1                   0.798893  
2                   0.666838  
3                   1.402568  
4                   0.644538  
...                      ...  
1653                0.783653  
1654                0.820293  
1655                0.652442  
1656                1.385799  
1657                0.750087  

[1658 rows x 3 columns]

In [354]:
ind_cols = [
    'Catholic',
    'School Locale',
    'Faculty Avg. Salary',
    'Admission Rate',
    'Percent of Undergraduates that Receive Federal Loan',
    'Percent Males',
    'Percent Females',
    'Out-In State Tuition Ratio',
    'Enrollment Size',
    'Avg. Cost',
    #'Median Househould Income',
    'Avg. Age of Entry',
    'Percent that Received Pell Grant',
]
independent = school_df[ind_cols]

In [355]:
independent

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
0            0             12               7709.0        0.917500   
1            0             12              11049.0        0.736600   
2            0             12               9688.0        0.825700   
3            0             12               7221.0        0.969000   
4            0             12              10291.0        0.826800   
...        ...            ...                  ...             ...   
1653         0             22               6173.0        0.989100   
1654         0             13               7297.0        0.845800   
1655         0             41               7320.0        0.741620   
1656         0             11               4775.0        0.803999   
1657         0             12               3380.0        0.286400   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
0                                                0.7361           0.3967   
1                                                0.4798           0.3890   
2                                                0.3976           0.5810   
3                                                0.8232           0.3691   
4                                                0.3802           0.4451   
...                                                 ...              ...   
1653                                             0.5356           0.4648   
1654                                             0.7416           0.4383   
1655                                             0.6038           0.2674   
1656                                             0.4779           0.3539   
1657                                             0.5484           0.5316   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  \
0              0.6033                    1.858939           5271.0   
1              0.6110                    2.380952          13328.0   
2              0.4190                    2.114548           7785.0   
3              0.6309                    1.752439           3750.0   
4              0.5549                    2.806122          31900.0   
...               ...                         ...              ...   
1653           0.5352                    1.000000            796.0   
1654           0.5617                    1.000000           2642.0   
1655           0.7326                    1.000000           6859.0   
1656           0.6461                    1.786487          28106.0   
1657           0.4684                    1.000000            348.0   

         Avg. Cost  Avg. Age of Entry  Percent that Received Pell Grant  
0     23053.000000                 20                            0.7019  
1     24495.000000                 23                            0.3512  
2     23917.000000                 22                            0.2536  
3     21866.000000                 20                            0.7627  
4     29872.000000                 21                            0.1772  
...            ...                ...                               ...  
1653  44301.000000                 22                            0.2618  
1654  30150.000000                 21                            0.4189  
1655  27500.000000                 31                            0.4844  
1656  12257.254193                 32                            0.5471  
1657  20752.000000                 28                            0.6290  

[1658 rows x 12 columns]

In [356]:
x_train, x_val, y_train, y_val = \
    train_test_split(independent, dependent, test_size = 0.30, random_state=42)

In [357]:
print(f'Training set has {x_train.shape[0]} observations')

Training set has 1160 observations


In [358]:
print(f'Validation set has {x_val.shape[0]} observations')

Validation set has 498 observations


In [359]:
def estimate_model(model, x, y):
    '''
    Performs 5-fold cross validation on model and returns dictionary with run time info & scoring metric info
       model - Model to be run and estimated
       x - matrix input independent variable observations
       y - matrix of output dependent variable observations
    '''
    cv = KFold(n_splits=5, random_state=42, shuffle=True)
    return cross_validate(model,
                          x,
                          y,
                          cv=cv,
                          scoring=('r2','neg_mean_absolute_error', 'neg_mean_squared_error'))

In [360]:
def get_means(results_dictionary):
    '''
    Returns average of all keys inside dictionary. 
    results_dictionary must have keys with numeric values
    '''
    if type(results_dictionary) != dict: return None
    average_dict = {}
    for key, val in results_dictionary.items():
        key += ' average'
        average_dict[key] = val.mean()
    return average_dict

In [361]:
def print_dictionary_elts(dictionary):
    '''
    Pretty print key/value pairs of a dictionary
    '''
    for key,val in dictionary.items():
        print(f'{key}: {val}')

In [362]:
## Multioutput Ridge Regression

In [363]:
ridge = MultiOutputRegressor(Ridge(random_state=42))

In [364]:
ridge_results = estimate_model(ridge, x_train, y_train) 

In [365]:
ridge_results

{'fit_time': array([0.01396322, 0.01196766, 0.01296091, 0.01296425, 0.01096916]),
 'score_time': array([0.01496458, 0.01197028, 0.01396251, 0.01296711, 0.01296711]),
 'test_r2': array([0.55378777, 0.54235183, 0.52042703, 0.50962874, 0.59225912]),
 'test_neg_mean_absolute_error': array([-0.08900597, -0.09502374, -0.09432756, -0.09142488, -0.08240544]),
 'test_neg_mean_squared_error': array([-0.01731404, -0.02018302, -0.01866815, -0.01829198, -0.01401233])}

In [366]:
print_dictionary_elts(get_means(ridge_results))

fit_time average: 0.012565040588378906
score_time average: 0.013366317749023438
test_r2 average: 0.5436908976559913
test_neg_mean_absolute_error average: -0.09043751779071581
test_neg_mean_squared_error average: -0.01769390253387615


In [367]:
## Multioutput Lasso Regression

In [368]:
lasso = MultiOutputRegressor(Lasso(random_state=42))

In [369]:
lasso_results = estimate_model(lasso, x_train, y_train)

In [370]:
lasso_results

{'fit_time': array([0.01695681, 0.01096845, 0.01296568, 0.0408926 , 0.01196456]),
 'score_time': array([0.0149591 , 0.00797868, 0.00897574, 0.0109725 , 0.01097369]),
 'test_r2': array([0.50051178, 0.4553953 , 0.42720522, 0.38212906, 0.47387957]),
 'test_neg_mean_absolute_error': array([-0.10040733, -0.10528939, -0.10665296, -0.10438655, -0.0943074 ]),
 'test_neg_mean_squared_error': array([-0.0199994 , -0.02361957, -0.02231649, -0.02263804, -0.01824975])}

In [371]:
print_dictionary_elts(get_means(lasso_results))

fit_time average: 0.01874961853027344
score_time average: 0.010771942138671876
test_r2 average: 0.44782418513932865
test_neg_mean_absolute_error average: -0.10220872800474927
test_neg_mean_squared_error average: -0.021364648593576712


In [372]:
## Multioutput Elastic Net Regression

In [373]:
elasticnet = MultiOutputRegressor(ElasticNet(random_state=42))

In [374]:
elasticnet_results = estimate_model(elasticnet, x_train, y_train)

In [375]:
elasticnet_results

{'fit_time': array([0.01399493, 0.00894284, 0.00897241, 0.01492786, 0.00997376]),
 'score_time': array([0.00795054, 0.00997686, 0.01000452, 0.01396608, 0.01196671]),
 'test_r2': array([0.50050219, 0.45546849, 0.42719067, 0.38214249, 0.47384543]),
 'test_neg_mean_absolute_error': array([-0.10041331, -0.1052758 , -0.10665118, -0.10437992, -0.09432855]),
 'test_neg_mean_squared_error': array([-0.0200006 , -0.02361574, -0.02231929, -0.02263491, -0.01825117])}

In [376]:
print_dictionary_elts(get_means(elasticnet_results))

fit_time average: 0.011362361907958984
score_time average: 0.010772943496704102
test_r2 average: 0.44782985245101853
test_neg_mean_absolute_error average: -0.10220975175806654
test_neg_mean_squared_error average: -0.021364343301138698


In [377]:
## Multioutput Linear Regression

In [378]:
linreg = MultiOutputRegressor(LinearRegression())

In [379]:
linreg_results = estimate_model(linreg, x_train, y_train)

In [380]:
linreg_results

{'fit_time': array([0.01595497, 0.01396608, 0.00906444, 0.00800085, 0.00957489]),
 'score_time': array([0.0139637 , 0.00996804, 0.00897884, 0.00701308, 0.00701571]),
 'test_r2': array([0.55315773, 0.54170992, 0.52123145, 0.51012785, 0.59142278]),
 'test_neg_mean_absolute_error': array([-0.08872933, -0.09508126, -0.09427414, -0.0913807 , -0.08261372]),
 'test_neg_mean_squared_error': array([-0.01732532, -0.02019831, -0.01863502, -0.01829545, -0.014051  ])}

In [381]:
print_dictionary_elts(get_means(linreg_results))

fit_time average: 0.011312246322631836
score_time average: 0.009387874603271484
test_r2 average: 0.5435299458565158
test_neg_mean_absolute_error average: -0.09041582926310393
test_neg_mean_squared_error average: -0.017701021434513745


In [382]:
randomforest = MultiOutputRegressor(ensemble.RandomForestRegressor())

In [383]:
randomforest_results = estimate_model(randomforest, x_train, y_train)

In [384]:
randomforest_results

{'fit_time': array([1.89320016, 1.82660151, 1.87592077, 1.83973527, 1.81233764]),
 'score_time': array([0.04188657, 0.04131866, 0.04187059, 0.04487467, 0.0428865 ]),
 'test_r2': array([0.64292712, 0.63483902, 0.61565094, 0.57546646, 0.64070662]),
 'test_neg_mean_absolute_error': array([-0.07812829, -0.08271186, -0.08259573, -0.08061539, -0.07474462]),
 'test_neg_mean_squared_error': array([-0.01253846, -0.01496816, -0.01365675, -0.01512994, -0.01191759])}

In [385]:
print_dictionary_elts(get_means(randomforest_results))

fit_time average: 1.8495590686798096
score_time average: 0.04256739616394043
test_r2 average: 0.6219180321726887
test_neg_mean_absolute_error average: -0.0797591806460799
test_neg_mean_squared_error average: -0.013642180538542655


In [386]:
## Random Forest Regression has the best error and r2 results even if it is a bit slower than the 
## other models, so this is the model that we will run validation on

In [387]:
randomforest.fit(x_train, y_train)

MultiOutputRegressor(estimator=RandomForestRegressor())

In [388]:
predictions = randomforest.predict(x_val)

In [389]:
predictions 

array([[0.688264  , 0.577867  , 1.01271158],
       [0.772498  , 0.605919  , 0.71112896],
       [0.611942  , 0.335991  , 0.84978358],
       ...,
       [0.758517  , 0.515782  , 0.73424885],
       [0.73155901, 0.521921  , 0.73832809],
       [0.76614077, 0.595418  , 0.72354862]])

In [390]:
mae = metrics.mean_absolute_error(y_val, predictions, multioutput='raw_values')
mae

array([0.06333613, 0.07202067, 0.1067513 ])

In [391]:
mse = metrics.mean_squared_error(y_val, predictions, multioutput='raw_values')
mse

array([0.01113918, 0.01020593, 0.02227087])

In [392]:
r2 = metrics.r2_score(y_val, predictions, multioutput='raw_values')
r2

array([0.51150614, 0.72716914, 0.60716081])

In [393]:
print(f'Average MAE is {mae.mean()}')
print(f'Average MSE is {mse.mean()}')
print(f'Average r-squared is {r2.mean()}')

Average MAE is 0.08070269921113588
Average MSE is 0.014538660776112567
Average r-squared is 0.6152786983411103


In [394]:
duquesne = school_df[school_df['School Name']=='Duquesne University']
duquesne

School Name School State Zip Code  School Locale  \
1105  Duquesne University           PA    15282             11   

      Rate of Full Time Faculty  Faculty Avg. Salary  Enrollment Size  \
1105                     0.5171               9367.0           5837.0   

      Percent Males  Percent Females  4 Year Retention Rate  ...  \
1105         0.3637           0.6363                 0.8547  ...   

      150% 4 Year Completion Rate (Pooled)  \
1105                                0.8038   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
1105                                 0.849254                    0.025   

      Undergraduate Federal Loan Repayment Rate  Catholic  Average Net Price  \
1105                                   0.909865         1            29309.0   

      Out-In State Tuition Ratio  Debt to Earnings Ratio  \
1105                         1.0                0.502213   

      Male to Female Ratio  Cluster (hier)  
1105              0.571586              40  

[1 rows x 26 columns]

In [395]:
duq_ind = duquesne[ind_cols]
duq_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [396]:
duq_dep = duquesne[dep_cols]
duq_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [397]:
duq_ind.shape

(1, 12)

In [398]:
def get_predictions(model, independent):
    '''
    Returns model predictions based on independent variables passed as an argument.
    '''
    return model.predict(independent)

In [399]:
def get_pred_errors(model, independent, actual_dependent):
    '''
    Returns MSE and MAE of predictions from the specified model
    '''
    predictions = get_predictions(model, independent)
    error_dict = {}
    error_dict['MSE'] = \
        metrics.mean_squared_error(actual_dependent, predictions, multioutput='raw_values')
    error_dict['MAE'] = \
        metrics.mean_absolute_error(actual_dependent, predictions, multioutput='raw_values')
    return error_dict

In [400]:
def get_difference(actual, predicted):
    '''
    Returns the difference actual-predicted
    '''
    return actual - predicted

In [401]:
for i in duq_dep: print(i)

4 Year Retention Rate
150% 4 Year Completion Rate (Pooled)
Debt to Earnings Ratio


In [402]:
duq_predicted =get_predictions(randomforest, duq_ind)
duq_predicted

array([[0.844455  , 0.734662  , 0.51234785]])

In [403]:
duq_pred_dict = {
    'Predicted 4 Year Retention Rate' : duq_predicted.tolist()[0][0],
    'Predicted 150% 4 Year Completion Rate (Pooled)' : duq_predicted.tolist()[0][1],
    'Predicted Debt to Earnings Ratio' : duq_predicted.tolist()[0][2]
}
duq_predicted_df = pd.DataFrame(data=duq_pred_dict, index=['Predicted'])
duq_predicted_df

Predicted 4 Year Retention Rate  \
Predicted                         0.844455   

           Predicted 150% 4 Year Completion Rate (Pooled)  \
Predicted                                        0.734662   

           Predicted Debt to Earnings Ratio  
Predicted                          0.512348

In [404]:
difference = duq_dep - duq_predicted

In [405]:
difference

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105               0.010245                              0.069138   

      Debt to Earnings Ratio  
1105               -0.010135

In [406]:
duq_mse = metrics.mean_squared_error(duq_dep, duq_predicted, multioutput='raw_values')
duq_mse.mean()

0.0016625810881250433

In [407]:
duq_mae = metrics.mean_absolute_error(duq_dep, duq_predicted, multioutput='raw_values')
duq_mae.mean()

0.029839365735333634

In [408]:
duq_error = get_means(get_pred_errors(randomforest, duq_ind, duq_dep))
print_dictionary_elts(duq_error)

MSE average: 0.0016625810881250433
MAE average: 0.029839365735333634


In [409]:
# Increase admission rate and see what the result is for the dependent variables
pretend1 = duquesne.copy()
pretend1_ind = pretend1[ind_cols]
pretend1_dep = pretend1[dep_cols]

In [410]:
pretend1_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [411]:
pretend1_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [412]:
pretend1_ind.loc[pretend1_ind['Admission Rate']==0.7433, 'Admission Rate'] = 1.0
pretend1_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0             1.0   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [413]:
predicted = get_predictions(randomforest, pretend1_ind)
predicted

array([[0.851941 , 0.711947 , 0.5513345]])

In [414]:
get_difference(pretend1_dep, predicted)

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105               0.002759                              0.091853   

      Debt to Earnings Ratio  
1105               -0.049122

In [415]:
# Decrease Average Cost and see what the result is for the dependent variables
pretend2 = duquesne.copy()
pretend2_ind = pretend2[ind_cols]
pretend2_dep = pretend2[dep_cols]

In [416]:
pretend2_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [417]:
pretend2_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [418]:
pretend2_ind.loc[pretend2_ind['Avg. Cost']==53904.0, 'Avg. Cost'] = 60000.0
pretend2_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    60000.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [419]:
predicted = get_predictions(randomforest, pretend2_ind)
predicted

array([[0.842904 , 0.734323 , 0.4706906]])

In [420]:
get_difference(pretend2_dep, predicted)

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105               0.011796                              0.069477   

      Debt to Earnings Ratio  
1105                0.031522

In [421]:
# Increase % that receive pell grant and see what happens to dependent variables
pretend3 = duquesne.copy()
pretend3_ind = pretend3[ind_cols]
pretend3_dep = pretend3[dep_cols]

In [422]:
pretend3_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [423]:
pretend3_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [424]:
pretend3_ind.loc[pretend3_ind['Percent that Received Pell Grant']==0.1923, 'Percent that Received Pell Grant'] = 0.4
pretend3_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                               0.4

In [425]:
predicted = get_predictions(randomforest, pretend3_ind)
predicted

array([[0.78738332, 0.653376  , 0.66454062]])

In [426]:
get_difference(pretend3_dep, predicted)

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105               0.067317                              0.150424   

      Debt to Earnings Ratio  
1105               -0.162328

In [427]:
# Decrease % that receive pell grant and see what happens to dependent variables
pretend4 = duquesne.copy()
pretend4_ind = pretend4[ind_cols]
pretend4_dep = pretend4[dep_cols]

In [428]:
pretend4_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [429]:
pretend4_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [430]:
pretend4_ind.loc[pretend4_ind['Percent that Received Pell Grant']==0.1923, 'Percent that Received Pell Grant'] = 0.05
pretend4_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                              0.05

In [431]:
predicted = get_predictions(randomforest, pretend4_ind)
predicted

array([[0.859501  , 0.745017  , 0.50327385]])

In [432]:
# Increase faculty average salary
pretend5 = duquesne.copy()
pretend5_ind = pretend5[ind_cols]
pretend5_dep = pretend5[dep_cols]

In [433]:
pretend5_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [434]:
pretend5_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [435]:
pretend5_ind.loc[pretend5_ind['Faculty Avg. Salary']==9367.0, 'Faculty Avg. Salary'] = 12000
pretend5_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11              12000.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [436]:
predictions = get_predictions(randomforest, pretend5_ind)
predictions

array([[0.853883  , 0.733837  , 0.51630392]])

In [437]:
# Change catholic to 0 (non-catholic)
pretend6 = duquesne.copy()
pretend6_ind = pretend6[ind_cols]
pretend6_dep = pretend6[dep_cols]

In [438]:
pretend6_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [439]:
pretend6_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [440]:
pretend6_ind.loc[pretend6_ind['Catholic']==1, 'Catholic'] = 0
pretend6_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         0             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [441]:
predictions = get_predictions(randomforest, pretend6_ind)
predictions

array([[0.845943 , 0.733612 , 0.5343503]])

In [442]:
# Increase admission rate and faculty average salary
pretend7 = duquesne.copy()
pretend7_ind = pretend7[ind_cols]
pretend7_dep = pretend7[dep_cols]

In [443]:
pretend7_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [444]:
pretend7_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [445]:
pretend7_ind.loc[pretend7_ind['Admission Rate']==0.7433, 'Admission Rate'] = 0.85
pretend7_ind.loc[pretend7_ind['Faculty Avg. Salary']==9367.0, 'Faculty Avg. Salary'] = 12000
pretend7_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11              12000.0            0.85   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [446]:
predictions = get_predictions(randomforest, pretend7_ind)
predictions

array([[0.858921  , 0.72365   , 0.52710651]])

In [523]:
# Increase average cost and admission rate
pretend8 = duquesne.copy()
pretend8_ind = pretend8[ind_cols]
pretend8_dep = pretend8[dep_cols]

In [524]:
pretend8_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [525]:
pretend8_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [526]:
pretend8_ind.loc[pretend8_ind['Admission Rate']==0.7433, 'Admission Rate'] = .90
pretend8_ind.loc[pretend8_ind['Avg. Cost']==53904.0, 'Avg. Cost'] = 63000.0
pretend8_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0             0.9   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    63000.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [527]:
predictions = get_predictions(randomforest, pretend8_ind)
predictions

array([[0.851376  , 0.720715  , 0.49937427]])

In [452]:
# Increase enrollment size
pretend9 = duquesne.copy()
pretend9_ind = pretend9[ind_cols]
pretend9_dep = pretend9[dep_cols]

In [453]:
pretend9_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [454]:
pretend9_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [455]:
pretend9_ind.loc[pretend9_ind['Enrollment Size']==5837.0, 'Enrollment Size'] = 8000.0
pretend9_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           8000.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [456]:
predictions = get_predictions(randomforest, pretend9_ind)
predictions

array([[0.844653  , 0.734535  , 0.51502078]])

In [457]:
# Increase admission rate, average faculty salary, and average cost
pretend10= duquesne.copy()
pretend10_ind = pretend10[ind_cols]
pretend10_dep = pretend10[dep_cols]

In [458]:
pretend10_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [459]:
pretend10_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [460]:
pretend10_ind.loc[pretend10_ind['Admission Rate']==0.7433, 'Admission Rate'] = 0.85
pretend10_ind.loc[pretend10_ind['Avg. Cost']==53904.0, 'Avg. Cost'] = 60000.0
pretend10_ind.loc[pretend10_ind['Faculty Avg. Salary']==9367.0, 'Faculty Avg. Salary'] = 10000
pretend10_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_in

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11              10000.0            0.85   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    60000.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [461]:
predictions = get_predictions(randomforest, pretend10_ind)
predictions

array([[0.852716 , 0.731759 , 0.4908505]])

In [462]:
# Decrease percent that receive federal loan
pretend11= duquesne.copy()
pretend11_ind = pretend11[ind_cols]
pretend11_dep = pretend11[dep_cols]

In [463]:
pretend11_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [464]:
pretend11_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [465]:
pretend11_ind.loc[pretend11_ind['Percent of Undergraduates that Receive Federal Loan']==0.6202, 'Percent of Undergraduates that Receive Federal Loan'] = 0.50
pretend11_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                                0.5           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [466]:
predictions = get_predictions(randomforest, pretend11_ind)
predictions

array([[0.852423  , 0.742008  , 0.53823037]])

In [467]:
# Set % Males = 0.50 = % Females
pretend12= duquesne.copy()
pretend12_ind = pretend12[ind_cols]
pretend12_dep = pretend12[dep_cols]

In [468]:
pretend12_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [469]:
pretend12_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [470]:
pretend12_ind.loc[pretend12_ind['Percent Males']==0.3637, 'Percent Males'] = 0.50
pretend12_ind.loc[pretend12_ind['Percent Females']==0.6363, 'Percent Females'] = 0.50
pretend12_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202              0.5   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105              0.5                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [471]:
predictions = get_predictions(randomforest, pretend12_ind)
predictions

array([[0.846721  , 0.731498  , 0.50090093]])

In [472]:
# Set % Males = 0.50 = % Females and increase Faculty salary
pretend13= duquesne.copy()
pretend13_ind = pretend13[ind_cols]
pretend13_dep = pretend13[dep_cols]

In [473]:
pretend13_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [474]:
pretend13_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [475]:
pretend13_ind.loc[pretend13_ind['Percent Males']==0.3637, 'Percent Males'] = 0.50
pretend13_ind.loc[pretend13_ind['Percent Females']==0.6363, 'Percent Females'] = 0.50
pretend13_ind.loc[pretend13_ind['Faculty Avg. Salary']==9367.0, 'Faculty Avg. Salary'] = 12000
pretend13_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_in

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11              12000.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202              0.5   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105              0.5                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [476]:
predictions = get_predictions(randomforest, pretend13_ind)
predictions

array([[0.856001 , 0.734741 , 0.5015935]])

In [477]:
# Set % Males = 0.50 = % Females and increase Faculty salary and cost
pretend14= duquesne.copy()
pretend14_ind = pretend14[ind_cols]
pretend14_dep = pretend14[dep_cols]

In [478]:
pretend14_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [479]:
pretend14_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [480]:
pretend14_ind.loc[pretend14_ind['Percent Males']==0.3637, 'Percent Males'] = 0.50
pretend14_ind.loc[pretend14_ind['Percent Females']==0.6363, 'Percent Females'] = 0.50
pretend14_ind.loc[pretend14_ind['Faculty Avg. Salary']==9367.0, 'Faculty Avg. Salary'] = 12000
pretend14_ind.loc[pretend14_ind['Avg. Cost']==53904.0, 'Avg. Cost'] = 60000.0
pretend14_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_in

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11              12000.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202              0.5   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105              0.5                         1.0           5837.0    60000.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [481]:
predictions = get_predictions(randomforest, pretend14_ind)
predictions

array([[0.854496  , 0.737549  , 0.49368064]])

In [482]:
# # Set % Males = 0.50 = % Females and increase Faculty salary and admission rate
pretend15= duquesne.copy()
pretend15_ind = pretend15[ind_cols]
pretend15_dep = pretend15[dep_cols]

In [483]:
pretend15_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [484]:
pretend15_dep

4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   

      Debt to Earnings Ratio  
1105                0.502213

In [485]:
pretend15_ind.loc[pretend15_ind['Percent Males']==0.3637, 'Percent Males'] = 0.50
pretend15_ind.loc[pretend15_ind['Percent Females']==0.6363, 'Percent Females'] = 0.50
pretend15_ind.loc[pretend15_ind['Faculty Avg. Salary']==9367.0, 'Faculty Avg. Salary'] = 12000
pretend15_ind.loc[pretend15_ind['Admission Rate']==0.7433, 'Admission Rate'] = 0.5
pretend15_ind

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_in

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11              12000.0             0.5   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202              0.5   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105              0.5                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [486]:
predictions = get_predictions(randomforest, pretend15_ind)
predictions

array([[0.9178    , 0.809589  , 0.46355571]])

In [487]:
# Decrease admission rate
pretend16= duquesne.copy()
pretend16_ind = pretend16[ind_cols]
pretend16_dep = pretend16[dep_cols]

In [488]:
pretend16_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [489]:
pretend16_ind.loc[pretend16_ind['Admission Rate']==0.7433, 'Admission Rate'] = 0.5

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [490]:
pretend16_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0             0.5   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [491]:
predictions = get_predictions(randomforest, pretend16_ind)
predictions

array([[0.86820674, 0.768375  , 0.5119826 ]])

In [492]:
# Decrease average cost
pretend17= duquesne.copy()
pretend17_ind = pretend16[ind_cols]
pretend17_dep = pretend16[dep_cols]

In [493]:
pretend17_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [494]:
pretend17_ind.loc[pretend17_ind['Avg. Cost']==53904.0, 'Avg. Cost'] = 40000.0

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [495]:
pretend17_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    40000.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [496]:
predictions = get_predictions(randomforest, pretend17_ind)
predictions

array([[0.83916  , 0.718235 , 0.5219745]])

In [528]:
# Decrease admission rate and average cost
pretend18= duquesne.copy()
pretend18_ind = pretend18[ind_cols]
pretend18_dep = pretend18[dep_cols]

In [529]:
pretend18_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [531]:
pretend18_ind.loc[pretend18_ind['Avg. Cost']==53904.0, 'Avg. Cost'] = 40000.0
pretend18_ind.loc[pretend18_ind['Admission Rate']==0.7433, 'Admission Rate'] = 0.5

C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)
C:\Users\devmy\anaconda3\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)


In [532]:
pretend18_ind

Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0             0.5   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    40000.0   

      Avg. Age of Entry  Percent that Received Pell Grant  
1105                 20                            0.1923

In [533]:
predictions = get_predictions(randomforest, pretend18_ind)
predictions

array([[0.85362   , 0.752627  , 0.52125888]])

In [502]:
school_names = [
    'Duquesne University',
    'Saint Joseph\'s',
    'Marquette University',
    'Seattle University'
]
school_names

['Duquesne University',
 "Saint Joseph's",
 'Marquette University',
 'Seattle University']

In [503]:
joseph = school_df['School Name'].str.contains('Saint Joseph\'s University')
for i in range(len(joseph)):
    if joseph[i]: joseph_idx = i #print(school_df['School Name'].values[i]) 
    

In [504]:
joseph = school_df[school_df['School Name']=='Saint Joseph\'s University']
joseph

School Name School State    Zip Code  School Locale  \
1176  Saint Joseph's University           PA  19131-1395             11   

      Rate of Full Time Faculty  Faculty Avg. Salary  Enrollment Size  \
1176                        1.0              10603.0           4679.0   

      Percent Males  Percent Females  4 Year Retention Rate  ...  \
1176         0.4597           0.5403                  0.882  ...   

      150% 4 Year Completion Rate (Pooled)  \
1176                                0.8063   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
1176                                 0.824887                    0.032   

      Undergraduate Federal Loan Repayment Rate  Catholic  Average Net Price  \
1176                                   0.915108         1            33375.0   

      Out-In State Tuition Ratio  Debt to Earnings Ratio  \
1176                         1.0                0.381326   

      Male to Female Ratio  Cluster (hier)  
1176              0.850824              40  

[1 rows x 26 columns]

In [505]:
portland = school_df[school_df['School Name']=='University of Portland']
portland

School Name School State    Zip Code  School Locale  \
1075  University of Portland           OR  97203-5798             11   

      Rate of Full Time Faculty  Faculty Avg. Salary  Enrollment Size  \
1075                     0.5415               9034.0           3773.0   

      Percent Males  Percent Females  4 Year Retention Rate  ...  \
1075         0.3912           0.6088                 0.9013  ...   

      150% 4 Year Completion Rate (Pooled)  \
1075                                0.8181   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
1075                                  0.89531                    0.007   

      Undergraduate Federal Loan Repayment Rate  Catholic  Average Net Price  \
1075                                   0.864614         1            36464.0   

      Out-In State Tuition Ratio  Debt to Earnings Ratio  \
1075                         1.0                0.475239   

      Male to Female Ratio  Cluster (hier)  
1075              0.642576              40  

[1 rows x 26 columns]

In [506]:
marquette = school_df[school_df['School Name'] == 'Marquette University']
marquette

School Name School State Zip Code  School Locale  \
1464  Marquette University           WI    53233             11   

      Rate of Full Time Faculty  Faculty Avg. Salary  Enrollment Size  \
1464                     0.5713              10158.0           8259.0   

      Percent Males  Percent Females  4 Year Retention Rate  ...  \
1464         0.4573           0.5427                 0.9001  ...   

      150% 4 Year Completion Rate (Pooled)  \
1464                                0.8315   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
1464                                 0.843265                    0.015   

      Undergraduate Federal Loan Repayment Rate  Catholic  Average Net Price  \
1464                                   0.880479         1            29756.0   

      Out-In State Tuition Ratio  Debt to Earnings Ratio  \
1464                         1.0                 0.53106   

      Male to Female Ratio  Cluster (hier)  
1464              0.842639              40  

[1 rows x 26 columns]

In [507]:
scranton = school_df[school_df['School Name']=='University of Scranton']
scranton

School Name School State    Zip Code  School Locale  \
1178  University of Scranton           PA  18510-4699             13   

      Rate of Full Time Faculty  Faculty Avg. Salary  Enrollment Size  \
1178                       0.68              10468.0           3675.0   

      Percent Males  Percent Females  4 Year Retention Rate  ...  \
1178         0.4256           0.5744                 0.8809  ...   

      150% 4 Year Completion Rate (Pooled)  \
1178                                0.8276   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
1178                                 0.856548                    0.019   

      Undergraduate Federal Loan Repayment Rate  Catholic  Average Net Price  \
1178                                   0.904833         1            34374.0   

      Out-In State Tuition Ratio  Debt to Earnings Ratio  \
1178                         1.0                0.454966   

      Male to Female Ratio  Cluster (hier)  
1178              0.740947              40  

[1 rows x 26 columns]

In [508]:
seattle = school_df[school_df['School Name']=='Seattle University']
seattle

School Name School State    Zip Code  School Locale  \
1428  Seattle University           WA  98122-4340             11   

      Rate of Full Time Faculty  Faculty Avg. Salary  Enrollment Size  \
1428                     0.6887               9588.0           4618.0   

      Percent Males  Percent Females  4 Year Retention Rate  ...  \
1428         0.3954           0.6046                  0.878  ...   

      150% 4 Year Completion Rate (Pooled)  \
1428                                0.7364   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
1428                                 0.787929                    0.021   

      Undergraduate Federal Loan Repayment Rate  Catholic  Average Net Price  \
1428                                   0.852979         1            34802.0   

      Out-In State Tuition Ratio  Debt to Earnings Ratio  \
1428                         1.0                0.432882   

      Male to Female Ratio  Cluster (hier)  
1428              0.653986              40  

[1 rows x 26 columns]

In [509]:
index = [
    'Duquesne University',
    'Saint Joseph\'s',
    'University of Portland'
    'Marquette University',
    'University of Scranton',
    'Seattle University'
]

In [510]:
peers = pd.concat([duquesne, joseph, portland, marquette, scranton, seattle])
peers

School Name School State    Zip Code  School Locale  \
1105        Duquesne University           PA       15282             11   
1176  Saint Joseph's University           PA  19131-1395             11   
1075     University of Portland           OR  97203-5798             11   
1464       Marquette University           WI       53233             11   
1178     University of Scranton           PA  18510-4699             13   
1428         Seattle University           WA  98122-4340             11   

      Rate of Full Time Faculty  Faculty Avg. Salary  Enrollment Size  \
1105                     0.5171               9367.0           5837.0   
1176                     1.0000              10603.0           4679.0   
1075                     0.5415               9034.0           3773.0   
1464                     0.5713              10158.0           8259.0   
1178                     0.6800              10468.0           3675.0   
1428                     0.6887               9588.0           4618.0   

      Percent Males  Percent Females  4 Year Retention Rate  ...  \
1105         0.3637           0.6363                 0.8547  ...   
1176         0.4597           0.5403                 0.8820  ...   
1075         0.3912           0.6088                 0.9013  ...   
1464         0.4573           0.5427                 0.9001  ...   
1178         0.4256           0.5744                 0.8809  ...   
1428         0.3954           0.6046                 0.8780  ...   

      150% 4 Year Completion Rate (Pooled)  \
1105                                0.8038   
1176                                0.8063   
1075                                0.8181   
1464                                0.8315   
1178                                0.8276   
1428                                0.7364   

      Percent Repaying Not in Default 5 Years  Three Year Default Rate  \
1105                                 0.849254                    0.025   
1176                                 0.824887                    0.032   
1075                                 0.895310                    0.007   
1464                                 0.843265                    0.015   
1178                                 0.856548                    0.019   
1428                                 0.787929                    0.021   

      Undergraduate Federal Loan Repayment Rate  Catholic  Average Net Price  \
1105                                   0.909865         1            29309.0   
1176                                   0.915108         1            33375.0   
1075                                   0.864614         1            36464.0   
1464                                   0.880479         1            29756.0   
1178                                   0.904833         1            34374.0   
1428                                   0.852979         1            34802.0   

      Out-In State Tuition Ratio  Debt to Earnings Ratio  \
1105                         1.0                0.502213   
1176                         1.0                0.381326   
1075                         1.0                0.475239   
1464                         1.0                0.531060   
1178                         1.0                0.454966   
1428                         1.0                0.432882   

      Male to Female Ratio  Cluster (hier)  
1105              0.571586              40  
1176              0.850824              40  
1075              0.642576              40  
1464              0.842639              40  
1178              0.740947              40  
1428              0.653986              40  

[6 rows x 26 columns]

In [511]:
peer_ind = peers[ind_cols]
peer_names = peers['School Name']
peer_ind['School Name'] = peer_names
peer_ind

<ipython-input-511-bd06756b9658>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  peer_ind['School Name'] = peer_names


Catholic  School Locale  Faculty Avg. Salary  Admission Rate  \
1105         1             11               9367.0          0.7433   
1176         1             11              10603.0          0.7498   
1075         1             11               9034.0          0.7665   
1464         1             11              10158.0          0.8296   
1178         1             13              10468.0          0.7632   
1428         1             11               9588.0          0.7848   

      Percent of Undergraduates that Receive Federal Loan  Percent Males  \
1105                                             0.6202           0.3637   
1176                                             0.5088           0.4597   
1075                                             0.4364           0.3912   
1464                                             0.4510           0.4573   
1178                                             0.6525           0.4256   
1428                                             0.5325           0.3954   

      Percent Females  Out-In State Tuition Ratio  Enrollment Size  Avg. Cost  \
1105           0.6363                         1.0           5837.0    53904.0   
1176           0.5403                         1.0           4679.0    61227.0   
1075           0.6088                         1.0           3773.0    61562.0   
1464           0.5427                         1.0           8259.0    57369.0   
1178           0.5744                         1.0           3675.0    60978.0   
1428           0.6046                         1.0           4618.0    61104.0   

      Avg. Age of Entry  Percent that Received Pell Grant  \
1105                 20                            0.1923   
1176                 21                            0.1374   
1075                 20                            0.1605   
1464                 19                            0.1849   
1178                 19                            0.1984   
1428                 21                            0.1933   

                    School Name  
1105        Duquesne University  
1176  Saint Joseph's University  
1075     University of Portland  
1464       Marquette University  
1178     University of Scranton  
1428         Seattle University

In [512]:
peer_ind.columns

Index(['Catholic', 'School Locale', 'Faculty Avg. Salary', 'Admission Rate',
       'Percent of Undergraduates that Receive Federal Loan', 'Percent Males',
       'Percent Females', 'Out-In State Tuition Ratio', 'Enrollment Size',
       'Avg. Cost', 'Avg. Age of Entry', 'Percent that Received Pell Grant',
       'School Name'],
      dtype='object')

In [513]:
col_order = [
       'School Name', 'Catholic', 'School Locale', 'Faculty Avg. Salary', 'Admission Rate',
       'Percent of Undergraduates that Receive Federal Loan', 'Percent Males',
       'Percent Females', 'Out-In State Tuition Ratio', 'Enrollment Size',
       'Avg. Cost', 'Avg. Age of Entry', 'Percent that Received Pell Grant',
       ]

In [514]:
ordered_peer_ind = peer_ind[col_order]
ordered_peer_ind

School Name  Catholic  School Locale  Faculty Avg. Salary  \
1105        Duquesne University         1             11               9367.0   
1176  Saint Joseph's University         1             11              10603.0   
1075     University of Portland         1             11               9034.0   
1464       Marquette University         1             11              10158.0   
1178     University of Scranton         1             13              10468.0   
1428         Seattle University         1             11               9588.0   

      Admission Rate  Percent of Undergraduates that Receive Federal Loan  \
1105          0.7433                                             0.6202     
1176          0.7498                                             0.5088     
1075          0.7665                                             0.4364     
1464          0.8296                                             0.4510     
1178          0.7632                                             0.6525     
1428          0.7848                                             0.5325     

      Percent Males  Percent Females  Out-In State Tuition Ratio  \
1105         0.3637           0.6363                         1.0   
1176         0.4597           0.5403                         1.0   
1075         0.3912           0.6088                         1.0   
1464         0.4573           0.5427                         1.0   
1178         0.4256           0.5744                         1.0   
1428         0.3954           0.6046                         1.0   

      Enrollment Size  Avg. Cost  Avg. Age of Entry  \
1105           5837.0    53904.0                 20   
1176           4679.0    61227.0                 21   
1075           3773.0    61562.0                 20   
1464           8259.0    57369.0                 19   
1178           3675.0    60978.0                 19   
1428           4618.0    61104.0                 21   

      Percent that Received Pell Grant  
1105                            0.1923  
1176                            0.1374  
1075                            0.1605  
1464                            0.1849  
1178                            0.1984  
1428                            0.1933

In [515]:
peer_dep = peers[dep_cols]
peer_names = peers['School Name']
peer_dep['School Name'] = peer_names
peer_dep

<ipython-input-515-820bd3d74270>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  peer_dep['School Name'] = peer_names


4 Year Retention Rate  150% 4 Year Completion Rate (Pooled)  \
1105                 0.8547                                0.8038   
1176                 0.8820                                0.8063   
1075                 0.9013                                0.8181   
1464                 0.9001                                0.8315   
1178                 0.8809                                0.8276   
1428                 0.8780                                0.7364   

      Debt to Earnings Ratio                School Name  
1105                0.502213        Duquesne University  
1176                0.381326  Saint Joseph's University  
1075                0.475239     University of Portland  
1464                0.531060       Marquette University  
1178                0.454966     University of Scranton  
1428                0.432882         Seattle University

In [516]:
peer_dep.columns

Index(['4 Year Retention Rate', '150% 4 Year Completion Rate (Pooled)',
       'Debt to Earnings Ratio', 'School Name'],
      dtype='object')

In [517]:
ordered_peer_dep = peer_dep[['School Name', '4 Year Retention Rate', '150% 4 Year Completion Rate (Pooled)',
       'Debt to Earnings Ratio']]
ordered_peer_dep

School Name  4 Year Retention Rate  \
1105        Duquesne University                 0.8547   
1176  Saint Joseph's University                 0.8820   
1075     University of Portland                 0.9013   
1464       Marquette University                 0.9001   
1178     University of Scranton                 0.8809   
1428         Seattle University                 0.8780   

      150% 4 Year Completion Rate (Pooled)  Debt to Earnings Ratio  
1105                                0.8038                0.502213  
1176                                0.8063                0.381326  
1075                                0.8181                0.475239  
1464                                0.8315                0.531060  
1178                                0.8276                0.454966  
1428                                0.7364                0.432882